### ISSUE TITLE
package-lock.json changes after npm install

### ISSUE THREAD

**Issue by xh3b4sd** [venturemark/webclient#18]
@marcusellison I was checking out https://github.com/venturemark/webclient/pull/16. In order to run it I had to `npm install` all new dependencies. Now my local copy is dirty with new changes in `package-lock.json`. I am not sure what to do with that and I feel like this is not quite right. 

```
$ git status --short
 M package-lock.json
```

```
$ git diff | head
diff --git a/package-lock.json b/package-lock.json
index b9b6b94..a2e96be 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,8 +1,17024 @@
 {
   "name": "webclient",
   "version": "0.1.0",
-  "lockfileVersion": 1,
+  "lockfileVersion": 2,
```

**Comment by marcusellison** [comment]
Let's talk through this. I'm not sure if it's just a symptom of the javascript ecosystem (we ignore for now) or if it's an issue we should plan to solve.

**Comment by marcusellison** [comment]
@xh3b4sd 
I've been going down a rabbit-hole trying to solve the new peer dependency bugs.
- conflicts are coming from multiple levels in the dependency tree. 
- Since npm 7 development version was only just released in October, many libraries (including create react app) haven't caught up.

I recommend that we either:
- revert down to latest Node LTS version  (6.x) 
or
- replace our ci `npm install` with `npm install --legacy-peer-deps` to unblock adoption of the latest version.

**Comment by xh3b4sd** [comment]
Ok, according to https://nodejs.org/en/download/releases we should then stick with node `v14.15.1` which gets us npm `v 6.14.8` again. I can fix the workflows and get the version on my machine right. You then need to take care about the version on your machine.

**Comment by xh3b4sd** [comment]
Brew is not good with the version mess. I use [nvm](https://github.com/nvm-sh/nvm) to manage the node versions. Same as with `gvm` for golang. 

```
brew uninstall node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | zsh
nvm install v14.15.1
```

You should then have the right version installed. Depending on your terminal session you need to open a new window after installation. 

```
$ node -v
v14.15.1
```
